"""empty message

Revision ID: 192c948b55f2
Revises: 47388fd1dbd4
Create Date: 2022-05-10 00:08:54.589683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '192c948b55f2'
down_revision = '47388fd1dbd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('moon', sa.String(length=120), nullable=False))
    op.add_column('planets', sa.Column('sun', sa.String(length=120), nullable=False))
    op.drop_column('planets', 'suns')
    op.drop_column('planets', 'moons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('moons', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('planets', sa.Column('suns', mysql.VARCHAR(length=120), nullable=False))
    op.drop_column('planets', 'sun')
    op.drop_column('planets', 'moon')
    # ### end Alembic commands ###
