"""empty message

Revision ID: 47388fd1dbd4
Revises: 6931082cd620
Create Date: 2022-05-09 23:53:26.910870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47388fd1dbd4'
down_revision = '6931082cd620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('moons', sa.String(length=120), nullable=False))
    op.add_column('planets', sa.Column('suns', sa.String(length=120), nullable=False))
    op.drop_column('planets', 'temp')
    op.drop_column('planets', 'mass')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('mass', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('planets', sa.Column('temp', mysql.VARCHAR(length=120), nullable=False))
    op.drop_column('planets', 'suns')
    op.drop_column('planets', 'moons')
    # ### end Alembic commands ###
